# Generated by Django 5.1.4 on 2025-03-19 07:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('category_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
            ],
            options={
                'verbose_name': 'Grocery Category',
                'verbose_name_plural': 'Grocery Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('customer_phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_gst', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='GST must be a valid 15-character alphanumeric code.', regex='^[0-9A-Z]{15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
            ],
            options={
                'verbose_name': 'Grocery Customer',
                'verbose_name_plural': 'Grocery Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_unit', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grocery Measurement',
                'verbose_name_plural': 'Grocery Measurements',
                'ordering': ['name_of_unit'],
            },
        ),
        migrations.CreateModel(
            name='GroceryOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dues_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('due', 'Due')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='GroceryApp.grocerycustomer')),
            ],
            options={
                'verbose_name': 'Grocery Order Detail',
                'verbose_name_plural': 'Grocery Order Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryOrderQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=200, unique=True)),
                ('quotation_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='GroceryApp.grocerycustomer')),
            ],
            options={
                'verbose_name': 'Grocery Order Quotation',
                'verbose_name_plural': 'Grocery Order Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('shop_owner_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('shop_phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('shop_email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('shop_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
            ],
            options={
                'verbose_name': 'Grocery Shop Details',
                'verbose_name_plural': 'Grocery Shop Details',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('shop_name', 'shop_phone'), name='unique__grocery_shop_details')],
            },
        ),
        migrations.CreateModel(
            name='GroceryStockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('product_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('margin_percent', models.IntegerField(default=0)),
                ('discount_percent', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(max_length=100)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='GroceryApp.grocerycategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='GroceryApp.groceryshopdetails')),
            ],
            options={
                'verbose_name': 'Grocery Stock Inventory',
                'verbose_name_plural': 'Grocery Stock Inventories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchased_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grocery_stock_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_stock', to='GroceryApp.grocerystockinventory')),
            ],
            options={
                'verbose_name': 'Grocery Stock',
                'verbose_name_plural': 'Grocery Stocks',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='GroceryQuotationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_products', to='GroceryApp.groceryorderquotation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='GroceryApp.grocerystockinventory')),
            ],
            options={
                'verbose_name': 'Grocery Quotation Product',
                'verbose_name_plural': 'Grocery Quotation Products',
            },
        ),
        migrations.AddField(
            model_name='groceryorderquotation',
            name='selected_product',
            field=models.ManyToManyField(related_name='quoted_products', through='GroceryApp.GroceryQuotationProduct', to='GroceryApp.grocerystockinventory'),
        ),
        migrations.CreateModel(
            name='GroceryOrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('Mobile', 'Mobile App'), ('Web', 'Web App')], default='Web', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='GroceryApp.groceryorderdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='GroceryApp.grocerystockinventory')),
            ],
            options={
                'verbose_name': 'Grocery Ordered Product',
                'verbose_name_plural': 'Grocery Ordered Products',
            },
        ),
        migrations.AddField(
            model_name='groceryorderdetails',
            name='selected_product',
            field=models.ManyToManyField(related_name='ordered_products', through='GroceryApp.GroceryOrderedProduct', to='GroceryApp.grocerystockinventory'),
        ),
        migrations.AddConstraint(
            model_name='grocerystockinventory',
            constraint=models.UniqueConstraint(fields=('shop', 'product_name'), name='unique_grocery_product_per_shop'),
        ),
    ]
