# Generated by Django 5.1.4 on 2025-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='garmentsstockinventory',
            name='unique_product_per_shop',
        ),
        migrations.AddConstraint(
            model_name='garmentsstockinventory',
            constraint=models.UniqueConstraint(fields=('shop', 'product_name'), name='unique_garments_product_per_shop'),
        ),
    ]
