# Generated by Django 5.1.4 on 2025-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsApp', '0002_remove_garmentsstockinventory_unique_product_per_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentsmeasurement',
            name='name_of_unit',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
