# Generated by Django 5.1.4 on 2025-03-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsApp', '0003_alter_garmentsmeasurement_name_of_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentsstockinventory',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='GarmentsApp.garmentsmeasurement'),
        ),
    ]
