# Generated by Django 5.1.4 on 2025-03-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsApp', '0004_alter_garmentsstockinventory_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmentsstockinventory',
            name='shop',
        ),
        migrations.CreateModel(
            name='GarmentsStockShopTagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garment_stock_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_tagged', to='GarmentsApp.garmentsstockinventory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_tagged', to='GarmentsApp.garmentsshopdetails')),
            ],
            options={
                'verbose_name': 'Garments Stock Shop Tagged',
                'verbose_name_plural': 'Garments Stock Shop Tagged',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='garmentsstockinventory',
            name='shop',
            field=models.ManyToManyField(related_name='stock_inventory', to='GarmentsApp.garmentsstockshoptagged'),
        ),
    ]
