# Generated by Django 5.1.4 on 2025-03-20 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsApp', '0005_remove_garmentsstockinventory_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmentsstockinventory',
            name='shop',
        ),
        migrations.DeleteModel(
            name='GarmentsStockShopTagged',
        ),
        migrations.AddField(
            model_name='garmentsstockinventory',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='GarmentsApp.garmentsshopdetails'),
            preserve_default=False,
        ),
    ]
