# Generated by Django 5.1.4 on 2025-03-20 11:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInvoiceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters long.')])),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A customer with this email already exists.'}, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 7 to 15 digits and contain only numbers.', regex='^\\d{7,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleInvoiceStockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_enterd_quantity', models.PositiveIntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
            ],
            options={
                'verbose_name': 'Stock Inventory',
                'verbose_name_plural': 'Stock Inventories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=200, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dues_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleInvoice.simpleinvoicecustomer')),
                ('invoice_item', models.ManyToManyField(related_name='invoice', to='SimpleInvoice.simpleinvoiceitem')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleCustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters long.')])),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 7 to 15 digits and contain only numbers.', regex='^\\d{7,15}$')])),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='SimpleInvoice.simpleinvoicecustomer')),
            ],
            options={
                'verbose_name': 'Customer History',
                'verbose_name_plural': 'Customer Histories',
                'ordering': ['-history_date'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dues_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled')], max_length=50)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='SimpleInvoice.simpleinvoice')),
            ],
            options={
                'verbose_name': 'Simple Invoice History',
                'verbose_name_plural': 'Simple Invoice Histories',
                'ordering': ['-history_date'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='SimpleInvoice.simpleinvoiceitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_histories', to='SimpleInvoice.simpleinvoicestockinventory')),
            ],
            options={
                'verbose_name': 'Simple Invoice Item History',
                'verbose_name_plural': 'Simple Invoice Item Histories',
                'ordering': ['-history_date'],
            },
        ),
        migrations.AddField(
            model_name='simpleinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='SimpleInvoice.simpleinvoicestockinventory'),
        ),
        migrations.CreateModel(
            name='SimpleInvoiceStockInventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('quantity', models.PositiveIntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('history_date', models.DateField(auto_now_add=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='SimpleInvoice.simpleinvoicestockinventory')),
            ],
            options={
                'verbose_name': 'Stock Inventory History',
                'verbose_name_plural': 'Stock Inventory Histories',
                'ordering': ['-history_date'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceStockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchased', models.PositiveBigIntegerField(default=0)),
                ('total_sold', models.PositiveBigIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_management', to='SimpleInvoice.simpleinvoicestockinventory')),
            ],
            options={
                'verbose_name': 'Stock Management',
                'verbose_name_plural': 'Stock Management',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceStockManagementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('history_status', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out')], default='stock_in', max_length=10)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SimpleInvoice.simpleinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_management_history', to='SimpleInvoice.simpleinvoicestockinventory')),
            ],
            options={
                'verbose_name': 'Stock Management History',
                'verbose_name_plural': 'Stock Management History',
                'ordering': ['-history_date'],
            },
        ),
    ]
