# Generated by Django 5.1.4 on 2025-03-20 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecustomerhistory',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='simpleinvoicecustomer',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A customer with this email already exists.'}, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
    ]
