# Generated by Django 5.1.4 on 2025-03-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0003_softwareid_user_sotware_id'),
        ('SimpleInvoice', '0002_alter_simplecustomerhistory_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleinvoiceitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Simple Invoice Item', 'verbose_name_plural': 'Simple Invoice Items'},
        ),
        migrations.AlterField(
            model_name='simpleinvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled')], default='unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='simpleinvoicehistory',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='InvoiceNumberGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_invoice_number', models.BigIntegerField()),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_number_generator', to='AuthorizationApp.softwareid')),
            ],
            options={
                'verbose_name': 'Invoice Number Generator',
                'verbose_name_plural': 'Invoice Number Generators',
            },
        ),
    ]
