# Generated by Django 5.1.4 on 2025-03-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInvoice', '0003_alter_simpleinvoiceitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleinvoicehistory',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='simpleinvoiceitemhistory',
            name='invoice_item',
        ),
        migrations.RemoveField(
            model_name='simpleinvoiceitemhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicestockinventoryhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicestockmanagement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicestockmanagementhistory',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicestockmanagementhistory',
            name='product',
        ),
        migrations.RenameField(
            model_name='simpleinvoicestockinventory',
            old_name='last_enterd_quantity',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='simpleinvoice',
            name='invoice_item',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicecustomer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicecustomer',
            name='email',
        ),
        migrations.AddField(
            model_name='simpleinvoiceitem',
            name='invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SimpleInvoice.simpleinvoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicenumbergenerate',
            name='last_invoice_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simpleinvoicecustomer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='simpleinvoicecustomer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='SimpleCustomerHistory',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceHistory',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceItemHistory',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceStockInventoryHistory',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceStockManagement',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceStockManagementHistory',
        ),
    ]
