# Generated by Django 5.1.4 on 2025-03-21 12:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0004_rename_contact_number_softwareid_company_number_and_more'),
        ('SimpleInvoice', '0004_remove_simpleinvoicehistory_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInvoiceMeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
            ],
            options={
                'verbose_name': 'Measurement Unit',
                'verbose_name_plural': 'Measurement Units',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='simpleinvoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='simpleinvoiceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='simpleinvoicecustomer',
            name='software',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='AuthorizationApp.softwareid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simpleinvoicestockinventory',
            name='software',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='AuthorizationApp.softwareid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simpleinvoicestockinventory',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SimpleInvoiceGenerateBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=200, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleInvoice.simpleinvoicecustomer')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generate_bill', to='AuthorizationApp.softwareid')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sub_unit', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='SimpleInvoice.simpleinvoicestockinventory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SimpleInvoice.simpleinvoicegeneratebill')),
            ],
            options={
                'verbose_name': 'Simple Invoice Item',
                'verbose_name_plural': 'Simple Invoice Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='simpleinvoicestockinventory',
            name='unit_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='SimpleInvoice.simpleinvoicemeasurementunit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SimpleInvoice',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceItem',
        ),
    ]
