# Generated by Django 5.1.4 on 2025-03-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInvoice', '0005_simpleinvoicemeasurementunit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleinvoicebillitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicebillitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicecustomer',
            name='software',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicegeneratebill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicegeneratebill',
            name='software',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicestockinventory',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='simpleinvoicestockinventory',
            name='software',
        ),
        migrations.DeleteModel(
            name='InvoiceNumberGenerate',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceBillItem',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceCustomer',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceGenerateBill',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceMeasurementUnit',
        ),
        migrations.DeleteModel(
            name='SimpleInvoiceStockInventory',
        ),
    ]
