# Generated by Django 5.1.4 on 2025-03-21 13:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthorizationApp', '0005_alter_user_software_type'),
        ('SimpleInvoice', '0006_remove_simpleinvoicebillitem_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInvoiceMeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
            ],
            options={
                'verbose_name': 'Measurement Unit',
                'verbose_name_plural': 'Measurement Units',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_invoice_number', models.BigIntegerField(default=0)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_number_generator', to='AuthorizationApp.softwareid')),
            ],
            options={
                'verbose_name': 'Invoice Number Generator',
                'verbose_name_plural': 'Invoice Number Generators',
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='AuthorizationApp.softwareid')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceGenerateBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=200, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleInvoice.simpleinvoicecustomer')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generate_bill', to='AuthorizationApp.softwareid')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceStockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='AuthorizationApp.softwareid')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='SimpleInvoice.simpleinvoicemeasurementunit')),
            ],
            options={
                'verbose_name': 'Stock Inventory',
                'verbose_name_plural': 'Stock Inventories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleInvoiceBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sub_unit', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SimpleInvoice.simpleinvoicegeneratebill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='SimpleInvoice.simpleinvoicestockinventory')),
            ],
            options={
                'verbose_name': 'Simple Invoice Item',
                'verbose_name_plural': 'Simple Invoice Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
