# Generated by Django 5.1.4 on 2025-03-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInvoice', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleinvoicestockinventory',
            old_name='software',
            new_name='company',
        ),
    ]
