# Generated by Django 5.1.4 on 2025-03-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0011_alter_companyid_expire_days'),
        ('SimpleInvoice', '0008_rename_software_simpleinvoicestockinventory_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceNumberGenerate',
            new_name='SimpleInvoiceNumberGenerate',
        ),
    ]
