# Generated by Django 5.1.4 on 2025-03-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInvoice', '0009_rename_invoicenumbergenerate_simpleinvoicenumbergenerate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleinvoicecustomer',
            old_name='software',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='simpleinvoicegeneratebill',
            old_name='software',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='simpleinvoicenumbergenerate',
            old_name='software',
            new_name='company',
        ),
    ]
