# Generated by Django 5.1.4 on 2025-03-21 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0002_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('short_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('contact_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number must be between 7 to 15 digits and contain only numbers.', regex='^\\d{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')])),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=200)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sotware_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='AuthorizationApp.softwareid'),
        ),
    ]
