# Generated by Django 5.1.4 on 2025-03-21 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0003_softwareid_user_sotware_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareid',
            old_name='contact_number',
            new_name='company_number',
        ),
        migrations.RemoveField(
            model_name='softwareid',
            name='name',
        ),
        migrations.RemoveField(
            model_name='softwareid',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sotware_id',
        ),
        migrations.AddField(
            model_name='softwareid',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwareid',
            name='expire_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softwareid',
            name='invoice_code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwareid',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='software_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='softwareid',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='software_type',
            field=models.CharField(choices=[('garments', 'Garments'), ('grocery', 'Grocery'), ('jewellery', 'Jewellery'), ('medical', 'Medical'), ('simple_invoice', 'Simple Invoice')], default='gm', max_length=255),
        ),
    ]
