# Generated by Django 5.1.4 on 2025-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0004_rename_contact_number_softwareid_company_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='software_type',
            field=models.CharField(choices=[('garments', 'Garments'), ('grocery', 'Grocery'), ('jewellery', 'Jewellery'), ('medical', 'Medical'), ('simple_invoice', 'Simple Invoice')], default='garments', max_length=255),
        ),
    ]
