# Generated by Django 5.1.4 on 2025-03-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0005_alter_user_software_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10)),
            ],
            options={
                'verbose_name': 'Software Type',
                'verbose_name_plural': 'Software Types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='software_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='AuthorizationApp.softwaretype'),
        ),
    ]
