# Generated by Django 5.1.4 on 2025-03-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0006_softwaretype_alter_user_software_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='software_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='AuthorizationApp.softwaretype'),
        ),
    ]
