# Generated by Django 5.1.4 on 2025-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0007_alter_user_software_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_name',
            field=models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App')], default='web', max_length=10),
        ),
    ]
