# Generated by Django 5.1.4 on 2025-03-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0008_user_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareid',
            name='software_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='software_id', to='AuthorizationApp.softwaretype'),
            preserve_default=False,
        ),
    ]
