# Generated by Django 5.1.4 on 2025-03-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0009_softwareid_software_type'),
        ('SimpleInvoice', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftwareID',
            new_name='CompanyID',
        ),
    ]
