# Generated by Django 5.1.4 on 2025-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationApp', '0010_rename_softwareid_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyid',
            name='expire_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
